name: fresh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  mongo_dart: ^0.5.0
  cupertino_icons: ^0.1.3
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.3
  firebase_core: ^1.0.2
  google_sign_in: ^5.0.1
  image_picker: ^0.7.4
  firebase_ml_vision: ^0.11.0
  flutter_image_compress: ^1.0.0
  carousel_slider: ^3.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  razorpay_flutter: ^1.2.0
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.1
  pointycastle: ^3.2.0
  crypto: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg