name: fresh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  mongo_dart: ^0.7.2
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.1.4
  firebase_auth_web: ^3.1.3
  firebase_core: ^1.8.0
  google_sign_in: ^5.2.0
  image_picker: ^0.8.4+3
  flutter_image_compress: ^1.1.0
  carousel_slider: ^4.0.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  razorpay_flutter: ^1.2.7
  flutter_secure_storage: ^4.2.1
  encrypt: ^5.0.1
  pointycastle: ^3.3.4
  crypto: ^3.0.1
  firebase_analytics: ^8.3.4
  intl: ^0.17.0
  firebase_messaging: ^10.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5
  uuid: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
